name: Auto Minify JS and CSS Files

on:
  workflow_dispatch:
  push:
    paths:
      - 'assets/**/*.js'
      - 'assets/**/*.css'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:3.1.0
        with:
          directory: 'assets'
          add_suffix: true
          inclusions: |-
            .*\.js$
            .*\.css$
          exclusions: |-
            (^|/)js/pdf_js/.*

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate minified JS and CSS files"
